driver:
  name: docker
  use_sudo: false
  customize: memory 1048
provisioner:
  name: chef_zero
verifier:
  name: inspec
  sudo_command: . /etc/profile;
platforms:
- name: ubuntu-14.04
  driver_config:
    instance_name: pandaseq-ubuntu1404
suites:
- name: default
  run_list:
  - recipe[pandaseq::default]
  verifier:
    inspec_tests:
    - test/smoke/default
  attributes:
